---
# tasks file for redis

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - redis

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - redis

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - redis

- name: Create Redis group
  become: yes
  group:
    name: "{{ redis_group }}"
    system: yes
    state: present
  tags:
    - redis

- name: Create Redis user
  become: yes
  user:
    name: "{{ redis_user }}"
    createhome: no
    group: "{{ redis_group }}"
    shell: /bin/false
    system: yes
    state: present
  tags:
    - redis

- name: Download Redis
  become: yes
  get_url:
    url: "{{ redis_url }}"
    dest: "{{ redis_download_dir }}"
    sha256sum: "{{ redis_sha256sum }}"
  tags:
    - redis

- name: Uncompress Redis archive
  become: yes
  unarchive:
    src: "{{ redis_download_dir }}/redis-{{ redis_version }}.tar.gz"
    dest: "{{ redis_download_dir }}"
    owner: root
    group: root
    copy: no
    creates: "{{ redis_download_dir }}/redis-{{ redis_version }}"
  tags:
    - redis

- name: Compile Redis
  become: yes
  command: make
  args:
    chdir: "{{ redis_src_dir }}"
    creates: "{{ redis_src_dir }}/src/redis-server"
  tags:
    - redis

- name: Install Redis
  become: yes
  command: make install
  args:
    chdir: "{{ redis_src_dir }}"
    creates: /usr/local/bin/redis-server
  tags:
    - redis

- name: Create Redis configuration directory
  become: yes
  file:
    path: /etc/redis
    owner: root
    group: "{{ redis_group }}"
    mode: 0755
    state: directory
  tags:
    - redis

- name: Create Redis log directory
  become: yes
  file:
    path: "{{ redis_log_dir }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0755
    state: directory
  tags:
    - redis

- name: Create Redis pid directory
  become: yes
  file:
    path: "{{ redis_pid_dir }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0755
    state: directory
  tags:
    - redis

- name: Create Redis working directory
  become: yes
  file:
    path: "{{ redis_working_directory }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0770
    state: directory
  tags:
    - redis

- name: Create Redis configuration file
  become: yes
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart redis
  tags:
    - redis

- name: Create Redis upstart script
  become: yes
  template:
    src: redis.upstart.j2
    dest: /etc/init/redis.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release|lower == 'trusty'
  notify:
    - restart redis
  tags:
    - redis

- name: Create Redis systemd service
  become: yes
  template:
    src: redis.service.j2
    dest: /etc/systemd/system/redis.service
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release|lower == 'xenial'
  notify:
    - reload systemd
    - restart redis
  tags:
    - redis

- name: Ensure Redis is started and enabled on boot
  become: yes
  service:
    name: "{{ redis_service_name }}"
    state: started
    enabled: yes
  tags:
    - redis
