---
# tasks file for redis (Ubuntu specific)

- name: Install Redis dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items: redis_packages
  tags: redis
