---
# tasks file for redis (Ubuntu specific)

- name: Install Redis dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ redis_packages }}"
  tags:
    - redis
